### ISSUE TITLE
Because cubes depends on mockito ^4.1.4 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by VomPom** [RafaelBarbosatec/cube#30] opened 2021-02-01 11:42 UTC
when I execute "flutter pub get" for the example,  get an error:
Because cubes depends on mockito ^4.1.4 which doesn't match any versions, version solving failed.

flutter doctor:
Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)

**Comment by RafaelBarbosatec** [comment] 2021-02-01 15:55
Thanks for the issue. 
Do you use any specific version of the mockito?
I'll try to switch to `any` to see if this resolves.

**Comment by RafaelBarbosatec** [comment] 2021-02-01 16:16
Try use version 0.10.7.

**Comment by RafaelBarbosatec** [comment] 2021-02-04 23:21
I can't reproduce this problem.
I will be closing the issue. Try to run the latest version, if you see the problem you can reopen the issue.

**Closed as completed by RafaelBarbosatec** 2021-02-04 23:21 UTC
